name: Deploy Serverless App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build the Serverless App
      run: |
        sam build

    - name: Deploy the Serverless App
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name your-stack-name --capabilities CAPABILITY_IAM
